#!/usr/bin/env python3
"""
Assembles solutions/B2BAgg.Core/src/Other/Customizations.xml from the
individual Entity.xml files in Entities/.

pac solution pack requires Other/Customizations.xml to be present.
Run this script whenever an Entity.xml is changed, then re-pack.
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC  = REPO / "solutions" / "B2BAgg.Core" / "src"
ENTITIES_DIR = SRC / "Entities"
OUTPUT = SRC / "Other" / "Customizations.xml"

def extract_entity_block(xml_text: str) -> str:
    """
    Pull the raw <entity Name="...">...</entity> block out of an
    Entity.xml file, preserving whitespace and comments.
    """
    # Find the opening tag (may have attributes)
    start = xml_text.find("<entity ")
    if start == -1:
        start = xml_text.find("<entity>")
    if start == -1:
        raise ValueError("No <entity> element found")

    # Find the matching closing tag (simple depth counter)
    depth = 0
    i = start
    while i < len(xml_text):
        if xml_text[i] == "<":
            # Skip XML comments <!-- ... -->
            if xml_text[i:i+4] == "<!--":
                end_comment = xml_text.find("-->", i + 4)
                if end_comment == -1:
                    break
                i = end_comment + 3
                continue
            # Check for closing tag
            if xml_text[i:i+8] == "</entity":
                depth -= 1
                if depth == 0:
                    end = xml_text.find(">", i) + 1
                    return xml_text[start:end]
            # Opening tag (not self-closing handled by depth ++)
            elif xml_text[i:i+7] == "<entity":
                depth += 1
        i += 1

    raise ValueError("Could not find matching </entity>")


def indent_block(block: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line
                     for line in block.splitlines())


def main():
    entity_names = sorted(p.name for p in ENTITIES_DIR.iterdir() if p.is_dir())
    if not entity_names:
        print(f"ERROR: No entity directories found in {ENTITIES_DIR}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(entity_names)} entities: {', '.join(entity_names)}")

    entities_xml_parts = []
    for name in entity_names:
        xml_file = ENTITIES_DIR / name / "Entity.xml"
        if not xml_file.exists():
            print(f"  WARNING: {xml_file} not found — skipping")
            continue
        raw = xml_file.read_text(encoding="utf-8")
        block = extract_entity_block(raw)
        indented = indent_block(block, 8)
        entities_xml_parts.append(
            f"    <Entity>\n"
            f"      <EntityInfo>\n"
            f"{indented}\n"
            f"      </EntityInfo>\n"
            f"      <FormXml />\n"
            f"      <Visualizations />\n"
            f"      <SavedQueries />\n"
            f"      <MobileOfflineFilters />\n"
            f"      <EntityPrivileges />\n"
            f"    </Entity>"
        )
        print(f"  + {name}")

    entities_section = "\n".join(entities_xml_parts)

    customizations = f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  Customizations.xml — auto-generated by scripts/gen-customizations.py
  DO NOT EDIT BY HAND. Edit the individual Entities/<name>/Entity.xml
  files and re-run the generator.
-->
<ImportExportXml version="9.2.24021.234" SolutionPackageVersion="9.2"
  languagecode="1033" generatedBy="CrmLive"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Entities>
{entities_section}
  </Entities>
  <Roles />
  <Workflows />
  <FieldSecurityProfiles />
  <Templates />
  <EntityMaps />
  <EntityRelationships />
  <OrganizationSettings />
  <optionsets />
  <CustomControls />
  <EntityDataProviders />
  <Languages>
    <Language>1033</Language>
  </Languages>
</ImportExportXml>
"""

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(customizations, encoding="utf-8")
    print(f"\nWritten: {OUTPUT} ({OUTPUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
